#!/bin/bash
# 2521-update
# Update and rebuild the docker image
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# Download any updates
git pull

# Rebuild the image
./scripts/2521-build

# TODO: Quality of life, automatically restart the image after building, only
# if it was running before
