#!/bin/bash
# 2521-down
# Shut down the COMP2521 docker image
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# Export group ID and user ID so that volumes can be attached properly
export UID
export GID=$(id -g)

# And shut down Docker
docker compose down
