#!/bin/bash
# 2521-sh
# Launch a Bash shell within the COMP2521 environment
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# TODO: Check that the image is running

# Launch bash within the image
export UID
export GID=$(id -g)
# Run entrypoint script as root
docker compose exec cs2521 "bash"
