#!/bin/bash
# 2521-sh
# Launch a Bash shell within the COMP2521 environment
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# Check that the image is running
# Grab container ID
# https://stackoverflow.com/a/34497614/6335363
# No need for sudo, sincer user should be added to Docker group
containerid=$(docker ps -aqf "name=docker-cs2521")
if [[ ! -n $containerid ]]; then
    echo "Looks like the docker-cs2521 container isn't running."
    echo "Start it by running 2521-up"
    exit 1
fi

# Launch bash within the image
export UID
export GID=$(id -g)
# Run entrypoint script as root
docker compose exec cs2521 "bash"
