#!/bin/bash
# 2521-update
# Update and rebuild the docker image
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# Download any updates
git pull

# Rebuild the image
echo "Building docker image. This may take a few minutes..."
docker compose up --build --no-start
