#!/bin/bash
# 2521-code
# Launch the running docker image in VS Code
#
# Author: Maddy Guthridge

# Check that the image is running
# Grab container ID
# https://stackoverflow.com/a/34497614/6335363
# No need for sudo, sincer user should be added to Docker group
containerid=$(docker ps -aqf "name=cs2521")
if [[ ! -n $containerid ]]; then
    echo "Looks like the cs2521 container isn't running."
    echo "Start it by running 2521-up"
    exit 1
fi

code_path=$(which code 2> /dev/null)
if [[ ! -n $code_path ]]; then
    echo "VS Code could not be found in your PATH variable."
    echo "On MacOS, you may need to run the 'Add code command to PATH' command"
    echo "By launching VS Code, then pressing Cmd+Shift+P and typing 'path'."
    echo "For other platforms, please ensure VS Code has been installed, and"
    echo "is present on your system's PATH variable."
    exit 1
fi

# Convert it to hex
# https://stackoverflow.com/a/46760046/6335363
hexid=$(echo -n "$containerid" | od -A n -t x1 | sed 's/ *//g')

# Attach to container, forwarding args to code executable
# https://cspotcode.com/posts/attach-vscode-to-container-from-cli
# This needs to be in a new window, otherwise, it quits immediately on MacOS
# if a local VS Code is running
code -n --remote="attached-container+${hexid}" $@
