#!/bin/bash
# 2521-update
# Update and rebuild the docker image
#
# Author: Maddy Guthridge

# cd to one above this script's directory
cd "$(dirname "$0")/.."

# Rebuild the image
echo "Building docker image. This may take a few minutes..."
export UID
export GID=$(id -g)
docker compose up --build --no-start
